### ISSUE TITLE
New artifacts are not published on any Maven repository

### ISSUE THREAD

**Issue by PattaFeuFeu** [ToxicBakery/Android-Nsd-Rx#7]
Something still seems to be slightly off. 😕 

After your recent release, I would have expected the artifacts to be published to the Sonatype repository in `publish.gradle` but that seems to not be happening for some reason.

See mvnrepository for available versions: https://mvnrepository.com/artifact/com.ToxicBakery.library.nsd.rx/android-nsd-rx

Or MavenCentral: https://central.sonatype.dev/artifact/com.ToxicBakery.library.nsd.rx/android-nsd-rx/1.0.22

According [to Sonatype, new URLs are supposed to be used for projects after 2021](https://central.sonatype.org/publish/publish-guide/#accessing-repositories), but the legacy URL this project uses should still work. (Beware, their Gradle guide still uses the old publishing plugin that’s not compatible with Gradle 7+)

@ToxicBakery

**Comment by ToxicBakery** [comment]
Moving issue to #8, I'm looking into it.
